### ISSUE TITLE
6 franko plays still not visible on staging..

### ISSUE THREAD

**Issue by DanilSko** [dracor-org/udracor#15]
Hi @cmil :) Is there any reason why I still do not see on staging these 6 plays? They were added in the PR from Dec 7, 2022

[franko-budka-ch-27.xml](https://github.com/dracor-org/udracor/blob/main/tei/franko-budka-ch-27.xml)
[franko-majster-chyrnjak.xml](https://github.com/dracor-org/udracor/blob/main/tei/franko-majster-chyrnjak.xml)
[franko-poslidnij-krejtsar.xml](https://github.com/dracor-org/udracor/blob/main/tei/franko-poslidnij-krejtsar.xml)
[franko-rjabyna.xml](https://github.com/dracor-org/udracor/blob/main/tei/franko-rjabyna.xml)
[franko-slavoj-i-khrudosh.xml](https://github.com/dracor-org/udracor/blob/main/tei/franko-slavoj-i-khrudosh.xml)
[franko-try-knjazi-na-odyn-prestol.xml](https://github.com/dracor-org/udracor/blob/main/tei/franko-try-knjazi-na-odyn-prestol.xml)

Should I fix sth with these files?

**Comment by cmil** [comment]
@DanilSko I'm not sure what happened. The webhook that triggers updates to the database seems to work, at least it did for a701e3a437f8b636d132338430c5d2d1fe427222. I reloaded the entire corpus. Everything should be up to date now.

**Comment by DanilSko** [comment]
@cmil thanks a lot, seems everything worked, they're there now! 
<img width="1428" alt="Screenshot 2023-02-13 at 11 51 15" src="https://user-images.githubusercontent.com/19728469/218438769-6f4bebef-229a-407f-88df-576dc431113a.png">
